### PR TITLE
plugins: Markdown: new setting MARKDOWN_EXTENSIONS

### PR DESCRIPTION
**Pull request by robert-figura**
This makes the Markdown extension much more versatile!

### CODE REVIEW

**Comment by fscherf** [comment]
Hi @robert-figura,

Looks good! The markdown support is very basic at the moment, and i appreciate code for this topic!

I have some change requests:

1. Please provide some documentation on how the new settings are meant to be used. Also tests would be great.

2. You change the default project template and add dependencies to it. Not everyone will need markdown. Please make this configurable like this for example:
```flamingo init wobsite project_name="Wobsite" markdown=True```

**Comment by robert-figura** [comment]
Huh, oh hi, there you are!

Yes, that makes sense! Thanks for the hint, I was just fooling around to get the example through the ci! Let me see if I get this.

**Comment by robert-figura** [comment]
Okay, I've put some extended examples into the documentation instead. I'm not sure how much testing would be useful. The static KaTeX rendering example would most certainly be too much, as it would require node.js on non-x86 platforms...

**Comment by fscherf** [comment]
Merged! Thanks for contributing :)

**Pull request closed without merging**
